/**
 * Queue diagnostics — issue #5, docs/02-API-CONTRACT.md §9.
 *
 * WHY THIS EXISTS. `echoJob` was built so that "is the queue running at all?"
 * has an answer that depends on nothing else. On a developer's machine that
 * answer is a log line. On a deployed host it is a log line nobody can reach —
 * which made #5's own acceptance criterion ("executes at approximately the
 * right time, locally AND on the deployed host") unverifiable, and would make
 * the first question in any future auto-release incident unanswerable.
 *
 * These endpoints are the reachable form of that answer: schedule a job that
 * does nothing, then ask whether it ran.
 *
 * ADMIN-only, and narrow on purpose. There is no endpoint here that enqueues an
 * arbitrary job onto an arbitrary queue — that would be a remote code path into
 * the worker. The only job this can schedule is the one that logs and exits.
 */

const express = require('express');

const { AppError } = require('../lib/errors.ts');
const { requireAuth, requireRole } = require('../middleware/auth.ts');
const { getQueue, deadLetterJobs, PREFIX } = require('../lib/queue.ts');
const echoJob = require('../jobs/echoJob.ts');

const router = express.Router();

/**
 * An hour. Long enough to test a delay that outlives a deploy, short enough
 * that nothing can be parked in the queue indefinitely.
 */
const MAX_DELAY_MS = 3600_000;

/**
 * POST /admin/queue/echo
 *
 * Schedules the do-nothing job and returns its id.
 *
 * `delayMs` defaults to 10,000 because that is the figure #5's criterion names.
 */
router.post(
  '/admin/queue/echo',
  requireAuth,
  requireRole('ADMIN', 'SUPER_ADMIN'),
  async (req: Req, res: Res, next: Next) => {
    try {
      const { delayMs, label } = req.body ?? {};

      const delay = parseDelay(delayMs);

      // Truncated rather than rejected: this is a diagnostic label, and failing
      // the check because someone pasted something long would be unhelpful.
      const message = String(label ?? 'queue diagnostic').slice(0, 120);

      const job = await getQueue(echoJob.QUEUE_NAME).add(
        echoJob.JOB_NAME,
        { message, scheduledAt: new Date().toISOString() },
        { delay }
      );

      res.status(202).json({
        job: {
          id: job.id,
          queue: echoJob.QUEUE_NAME,
          delayMs: delay,
          expectedAt: new Date(Date.now() + delay).toISOString(),
        },
      });
    } catch (err) {
      next(err);
    }
  }
);

/**
 * GET /admin/queue/echo/:id
 *
 * Whether it ran, and when.
 *
 * `ranAt` comes from the job's own return value, which is produced inside the
 * WORKER process. That is the part that matters: a `completed` state proves the
 * queue accepted and finished the job, but a timestamp generated by the
 * processor proves a worker executed it — which on a deployed host is exactly
 * the question being asked.
 */
router.get(
  '/admin/queue/echo/:id',
  requireAuth,
  requireRole('ADMIN', 'SUPER_ADMIN'),
  async (req: Req, res: Res, next: Next) => {
    try {
      const job = await getQueue(echoJob.QUEUE_NAME).getJob(req.params.id);
      if (!job) throw new AppError(404, 'No such job.');

      const state = await job.getState();

      res.json({
        job: {
          id: job.id,
          state,
          attemptsMade: job.attemptsMade,
          scheduledAt: job.data?.scheduledAt ?? null,
          expectedAt: new Date(job.timestamp + (job.opts?.delay ?? 0)).toISOString(),
          finishedAt: job.finishedOn ? new Date(job.finishedOn).toISOString() : null,
          ranAt: job.returnvalue?.ranAt ?? null,
          failedReason: job.failedReason ?? null,
        },
      });
    } catch (err) {
      next(err);
    }
  }
);

/**
 * GET /admin/queue/dead-letter
 *
 * Jobs that exhausted every retry.
 *
 * Nothing drains this queue automatically — that is the point (#5). It is a
 * record for a human, and until now it was a record no human could read without
 * shell access to the host.
 */
router.get(
  '/admin/queue/dead-letter',
  requireAuth,
  requireRole('ADMIN', 'SUPER_ADMIN'),
  async (req: Req, res: Res, next: Next) => {
    try {
      const limit = Math.min(Number(req.query.limit ?? 50) || 50, 200);
      const jobs = await deadLetterJobs(limit);

      res.json({
        prefix: PREFIX,
        total: jobs.length,
        jobs: jobs.map((job: import('bullmq').Job) => ({
          id: job.id,
          originalQueue: job.data?.queue ?? null,
          jobName: job.data?.jobName ?? null,
          failedReason: job.data?.failedReason ?? null,
          attemptsMade: job.data?.attemptsMade ?? null,
          failedAt: job.data?.failedAt ?? null,
        })),
      });
    } catch (err) {
      next(err);
    }
  }
);

/**
 * The requested delay, or the default.
 *
 * Unspecified — absent, `null`, or an empty string from a blank form field —
 * means the default, NOT zero. JSON carries neither `NaN` nor `Infinity`, so a
 * client whose own calculation failed sends `null`; reading that as "run now"
 * would turn a broken input into a silently different schedule.
 *
 * Everything else must be a number or a string that is one. `Number(true)` is
 * `1` and `Number([])` is `0`, so a bare `Number()` would accept a boolean as a
 * one-millisecond delay and an array as an immediate one.
 */
function parseDelay(value: unknown): number {
  if (value === undefined || value === null || value === '') return 10_000;

  if (typeof value !== 'number' && typeof value !== 'string') {
    throw new AppError(400, `delayMs must be a number between 0 and ${MAX_DELAY_MS}.`);
  }

  const delay = Number(value);
  if (!Number.isFinite(delay) || delay < 0 || delay > MAX_DELAY_MS) {
    throw new AppError(400, `delayMs must be a number between 0 and ${MAX_DELAY_MS}.`);
  }

  return delay;
}

module.exports = { router, parseDelay, MAX_DELAY_MS };
